// <auto-generated />
using System;
using GestorTareas.Infraestructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorTareas.Migrations
{
    [DbContext(typeof(GestorTareasContext))]
    [Migration("20260507174609_AnadirPasswordHashUser")]
    partial class AnadirPasswordHashUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorTareas.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DueTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GestorTareas.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UserTasks", b =>
                {
                    b.Property<int>("UsersListId")
                        .HasColumnType("int");

                    b.Property<int>("tasksListId")
                        .HasColumnType("int");

                    b.HasKey("UsersListId", "tasksListId");

                    b.HasIndex("tasksListId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("GestorTareas.Models.CompositeTask", b =>
                {
                    b.HasBaseType("GestorTareas.Models.Task");

                    b.Property<int>("CompositeTaskType")
                        .HasColumnType("int");

                    b.ToTable("CompositeTasks", (string)null);
                });

            modelBuilder.Entity("GestorTareas.Models.RecurringTask", b =>
                {
                    b.HasBaseType("GestorTareas.Models.Task");

                    b.Property<int>("RecurrenceRule")
                        .HasColumnType("int");

                    b.Property<int>("RecurringTasksCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable("RecurringTasks", (string)null);
                });

            modelBuilder.Entity("GestorTareas.Models.SimpleTask", b =>
                {
                    b.HasBaseType("GestorTareas.Models.Task");

                    b.ToTable("SimpleTasks");
                });

            modelBuilder.Entity("GestorTareas.Models.LinkedTask", b =>
                {
                    b.HasBaseType("GestorTareas.Models.CompositeTask");

                    b.Property<int?>("FKCompositeTaskId_Linked")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedTaskId")
                        .HasColumnType("int");

                    b.Property<int>("LinkedTaskOrder")
                        .HasColumnType("int");

                    b.HasIndex("FKCompositeTaskId_Linked");

                    b.HasIndex("LinkedTaskId");

                    b.ToTable("LinkedTasks", (string)null);
                });

            modelBuilder.Entity("GestorTareas.Models.SubTask", b =>
                {
                    b.HasBaseType("GestorTareas.Models.CompositeTask");

                    b.Property<int?>("FKCompositeTaskId_Sub")
                        .HasColumnType("int");

                    b.HasIndex("FKCompositeTaskId_Sub");

                    b.ToTable("SubTasks", (string)null);
                });

            modelBuilder.Entity("GestorTareas.Models.Task", b =>
                {
                    b.HasOne("GestorTareas.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserTasks", b =>
                {
                    b.HasOne("GestorTareas.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestorTareas.Models.Task", null)
                        .WithMany()
                        .HasForeignKey("tasksListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTareas.Models.CompositeTask", b =>
                {
                    b.HasOne("GestorTareas.Models.Task", null)
                        .WithOne()
                        .HasForeignKey("GestorTareas.Models.CompositeTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTareas.Models.RecurringTask", b =>
                {
                    b.HasOne("GestorTareas.Models.Task", null)
                        .WithOne()
                        .HasForeignKey("GestorTareas.Models.RecurringTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTareas.Models.SimpleTask", b =>
                {
                    b.HasOne("GestorTareas.Models.Task", null)
                        .WithOne()
                        .HasForeignKey("GestorTareas.Models.SimpleTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTareas.Models.LinkedTask", b =>
                {
                    b.HasOne("GestorTareas.Models.CompositeTask", null)
                        .WithMany("LinkedTaskList")
                        .HasForeignKey("FKCompositeTaskId_Linked");

                    b.HasOne("GestorTareas.Models.CompositeTask", null)
                        .WithOne()
                        .HasForeignKey("GestorTareas.Models.LinkedTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorTareas.Models.LinkedTask", null)
                        .WithMany("ListOfLinkedTasks")
                        .HasForeignKey("LinkedTaskId");
                });

            modelBuilder.Entity("GestorTareas.Models.SubTask", b =>
                {
                    b.HasOne("GestorTareas.Models.CompositeTask", null)
                        .WithMany("SubTaskList")
                        .HasForeignKey("FKCompositeTaskId_Sub");

                    b.HasOne("GestorTareas.Models.CompositeTask", null)
                        .WithOne()
                        .HasForeignKey("GestorTareas.Models.SubTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTareas.Models.CompositeTask", b =>
                {
                    b.Navigation("LinkedTaskList");

                    b.Navigation("SubTaskList");
                });

            modelBuilder.Entity("GestorTareas.Models.LinkedTask", b =>
                {
                    b.Navigation("ListOfLinkedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
