--Tabla USER
CREATE TABLE USERS(
Id INT IDENTITY(1,1) PRIMARY KEY,
UserName NVARCHAR(50) NOT NULL,
UserLastName NVARCHAR(80) NOT NULL,
Email NVARCHAR(100) NOT NULL,
UserActive BIT NOT NULL DEFAULT 1,
CreatedAt DATETIME DEFAULT GETDATE(),
UpdatedAt DATETIME DEFAULT NULL
);

--Tabla TASK
CREATE TABLE TASKS(
Id INT IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(30) NOT NULL,
Description NVARCHAR(500) NULL,
Priority NVARCHAR (15) NULL,
Status NVARCHAR (15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR(400) NULL
 );

--TABLA simpleTask
CREATE TABLE SIMPLETASKS(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    constraint FK_Task FOREIGN KEY (Id) REFERENCES Tasks(id)
);

 --TABLA COMPOSITETASK
CREATE TABLE CompositeTaskS(
    id int IDENTITY(1,1) PRIMARY KEY,
    CONSTRAINT FK_TASKS
    FOREIGN KEY (Id) REFERENCES Tasks(id)
);
 --TABLA SUBTASK
CREATE TABLE SubTaskS(
    Id INT IDENTITY(1,1) PRIMARY KEY,
CONSTRAINT FK_COMPOSITETASKS
FOREIGN KEY (Id) REFERENCES CompositeTaskS(ID)
);
 --TABLA LINKEDTASK
CREATE TABLE LinkedTaskS(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    taskOrder INT NOT NULL,
    CONSTRAINT FK_COMPOSITETASKS 
    FOREIGN KEY (Id) REFERENCES COMPOSITETASKS(ID)
);
 --TABLA RECURRING TASK
CREATE TABLE RecurringTasks(
    Id INT IDENTITY(1,1) PRIMARY KEY,
RecurrenceRule INT NOT NULL,
CONSTRAINT fk_recurringTasks
FOREIGN KEY (Id) REFERENCES Tasks(id)
);


