
USE GestorTareas;

--Tabla USER
CREATE TABLE Users
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL,
    UserLastName NVARCHAR(80) NOT NULL,
    UserEmail NVARCHAR(100) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    IsAdmin BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT NULL
);
GO
--Tabla TASK
CREATE TABLE Tasks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(30) NOT NULL,
    TaskDescription NVARCHAR(500) NULL,
    Priority NVARCHAR (15) NULL,
    Status NVARCHAR (15) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    DueTime DATETIME2 NULL,
    CancelReason NVARCHAR(400) NULL
);
GO
--TABLA simpleTask
CREATE TABLE SimpleTasks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CONSTRAINT FK_SimpleTasks_Tasks_Id FOREIGN KEY (Id) REFERENCES Tasks(Id)
);
GO
--TABLA COMPOSITETASK
CREATE TABLE CompositeTasks
(
    Id int IDENTITY(1,1) PRIMARY KEY,
    CompositeTaskType NVARCHAR (15) NOT NULL,
    CONSTRAINT FK_COMPOSITETASKS_TASKS_ID
    FOREIGN KEY (Id) REFERENCES Tasks(Id)
);
GO

--TABLA SUBTASK
CREATE TABLE SubTasks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CONSTRAINT FK_SUBTASKS_COMPOSITETASKS_ID
FOREIGN KEY (Id) REFERENCES CompositeTaskS(Id)
);
GO


--TABLA LINKEDTASK
CREATE TABLE LinkedTasks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    LinkedTaskOrder INT NOT NULL,
    CONSTRAINT FK_LINKED_COMPOSITETASKS_ID
    FOREIGN KEY (Id) REFERENCES COMPOSITETASKS(Id)
);
GO

--TABLA RECURRING TASK
CREATE TABLE RecurringTasks
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RecurrenceRule INT NOT NULL,
    RecurringTasksCount INT NOT NULL,
    CONSTRAINT FK_RECURRINGTASKS_TASKS_ID
FOREIGN KEY (Id) REFERENCES Tasks(Id)
);
GO


