--Tabla TASK
CREATE TABLE TASK(
Id INT IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(30) NOT NULL,
Description NVARCHAR() NULL,
Priority NVARCHAR
(15) NULL,
Status NVARCHAR1
(15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE
(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR NULL
 );

--TABLA simpleTask
CREATE TABLE SIMPLETASK(
    Id INT IDENTITY() PRIMARY KEY,
    Title NVARCHAR
(30) NOT NULL,
Description NVARCHAR
() NULL,
Priority NVARCHAR
(15) NULL,
Status NVARCHAR1
(15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE
(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR NULL,
FOREIGN KEY Id REFERENCES Task.Id ON Task
);

 --TABLA COMPOSITETASK
CREATE TABLE CompositeTask(
    Id INT IDENTITY() PRIMARY KEY,
    Title NVARCHAR
(30) NOT NULL,
Description NVARCHAR
() NULL,
Priority NVARCHAR
(15) NULL,
Status NVARCHAR1
(15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE
(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR NULL,
FOREIGN KEY Id REFERENCES Task.Id ON Task
);
 --TABLA SUBTASK
CREATE TABLE SubTask(
    Id INT IDENTITY() PRIMARY KEY,
    Title NVARCHAR
(30) NOT NULL,
Description NVARCHAR
() NULL,
Priority NVARCHAR
(15) NULL,
Status NVARCHAR1
(15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE
(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR NULL,
FOREIGN KEY Id REFERENCES Task.Id ON CompositeTask
);
 --TABLA LINKEDTASK
CREATE TABLE LinkedTask(
    Id INT IDENTITY() PRIMARY KEY,
    Title NVARCHAR
(30) NOT NULL,
Description NVARCHAR
() NULL,
Priority NVARCHAR
(15) NULL,
Status NVARCHAR1
(15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE
(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR NULL,
Order INT NOT NULL,
FOREIGN KEY Id REFERENCES Task.Id ON LinkedTask
);
 --TABLA RECURRING TASK
CREATE TABLE RecurringTask(
    Id INT IDENTITY() PRIMARY KEY,
    Title NVARCHAR
(30) NOT NULL,
Description NVARCHAR
() NULL,
Priority NVARCHAR
(15) NULL,
Status NVARCHAR1
(15) NULL,
CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE
(),
UpdatedAt DATETIME2  NOT NULL,
DueTime DATETIME2 NULL,
CancelReason NVARCHAR NULL,
RecurrenceRule INT NOT NULL,
FOREIGN KEY Id REFERENCES Task.Id ON Task
);
